### ISSUE TITLE
Support for strings and floats

### ISSUE THREAD

**Issue by GreyDireWolf** [FastFilter/xor_singleheader#12]
Currently I'm working on [python bindings](https://github.com/GreyDireWolf/pyxorfilter) of this C implementation of xorfilter. I was wondering if there would be any support for strings and floats in future.

**Comment by lemire** [comment]
Is the following statement in the README of any use to you?

> We are assuming that your set is made of 64-bit integers. If you have strings
or other data structures, you need to hash them first to a 64-bit integer. It
is not important to have a good hash function, but collisions should be unlikely
(~1/2^64).

In Python, you can rely on the builtin `hash` function to map arbitrary values to a hash value. So you want to take your inputs, map them to an array of hash values (via `hash`) and then pass that to the C code.

**Comment by GreyDireWolf** [comment]
@lemire Thanks for the idea. I'll look into it
