### ISSUE TITLE
The dangers of dup keys

### ISSUE THREAD

**Issue by mpope9** [FastFilter/xor_singleheader#13]
Hello!  Love the library.

I don't feel like the README talks about the dangers of duplicate keys enough (the infinite loop).  Not sure what the phrasing should be, but `You should ensure that you have no duplicated keys.` doesn't give the gravity of the situation correctly.

**Comment by mpope9** [comment]
Possibly a maximum number of iterations that is based of off the size of the keyspace can be used to return early with an error?

**Comment by lemire** [comment]
I agree that this is a concern that should be better addressed. It is improbable that you will ever have more than 2 or 3 trials. We should probably stop at this point (when the improbable happens) to look at the data more carefully. Infinite loops should be impossible.

**Comment by lemire** [comment]
I have put a limit on the number of iterations (100) so there should no longer be infinite loops, no matter what. Caller will get a false, and a somewhat long processing time. The 100 iterations default could be tuned (it is a compile-time parameter).

**Comment by mpope9** [comment]
Amazing!
