### ISSUE TITLE
Merging of 2 different bloom filters with same size 

### ISSUE THREAD

**Issue by Manoj-red-hat** [FastFilter/xor_singleheader#15]
Hi @lemire  was working on distributed bloom filters.

Is it possible to merge bloom filters like we do merging in regular bit based bloom filter by oring(|) bytes.

**Comment by thomasmueller** [comment]
No, unfortunately with xor filters this is not possible I'm afraid. You would need the keys to do that.
May I ask what is the use case?

**Comment by Manoj-red-hat** [comment]
**Here is the use case**

- Most of the big data tools be it spark or hive use bloom filter for reducing network overhead durning shuffle process.


**Example**

>Lets have a mapjoin on 2 tables large table (Table A) contains 10 billion ints and small table (Table B) contains 600 million. In order to do mapjoin we create hashtable of small table but due to memory constraint on single node we can't do this.

**So here is the solution**

lets have a cluster of 4 nodes
Divide small table into 4 bucket (150M)
Divide Big table into 4 bucket (1.2 Billion)
Now on each node we only need to craete 600/4 ~ 150 million entries hastable (which comes under single node limit)


***Now how we use bloom filter in that scenario***

In order to transfer each bucket element to their corresponding node we require **network shuffle**
**Due to large size ~2.5 bilion enteries per bucket its become bottleneck in performance**

***In order to mitigate this what we do***
>We first bucket small table, on each node we create bloom filter (having bloom bytes == original data size 600M)   of 150M bucketed data.
Node 1 : BloomFilter A (Bucket Data Node 1)
Node 2 : BloomFilter B (Bucket Data Node 2)
Node 3 : BloomFilter C (Bucket Data Node 3)
Node 4 : BloomFilter D (Bucket Data Node 4)
After that we serialize and transfer bloom bytes across each node.
On each node we do
BloomFilterFinal = BloomFilter A | B| C | D
This final merged bloom filter is used to filter out large table buckets data before sending to network for shuffle.
Thus we reduce intermediate shuffle bytes and once our shuffle data is complete
we do hash join to filter out false positive.

**Comment by Manoj-red-hat** [comment]
@lemire  @thomasmueller 
>If the original two filters are of the same size and have the same false positive rate, then the false positive rate of the merged Bloom filter will be roughly ten times higher! So for example, if the original two filters contained 4000 items each, and had a size of 40'000 bits. Then the false positive rate is about 0.8%. If you then merge those two filters, it will be a filter with 40'000 bits and 8000 items, and the false positive rate will be about 9%. Are you aware of this? Is it not a problem for you?


What happens if I know I need to create filter of 8000 items,
what I do map 4000 items each on 8000 items bloom filter for each of the two.

Say bloom A -> having bloom to handle 8000 item, but only first 4k mapped
Say bloom B -> having bloom to handle 8000 item, but only last 4k mapped

Final Bloom A|B will it work ?

**Comment by thomasmueller** [comment]
Yes what you describe works perfectly for Bloom filters! However I'm afraid for a xor filter, you would need to store the list of keys... There is no way to merge xor filters: xor filters are immutable.
