### ISSUE TITLE
Find rare elements using the filter

### ISSUE THREAD

**Issue by seryrzu** [FastFilter/xor_singleheader#23]
This is not an issue, but a question. Can I do the following query to the Xor filter: "does the given element appear definitely less than the threshold number of times"? Counting Bloom filter seems to be a traditional approach for that, but I wonder what is the current state-of-the-art library that allows that out of the box? I looked at [cuckoofilter library](https://github.com/efficient/cuckoofilter) and this operation is not supported (even though, I presume, it is possible: [filter-tutorial](https://bdupras.github.io/filter-tutorial/)). It would be great if Xor Filter allowed that. Otherwise, what would you recommend, maybe something from [fastfilter_cpp](https://github.com/FastFilter/fastfilter_cpp/)? If that matters, I plan to put up to 3 billion queries to the filter and search for elements that were added less than ~10 times.

Thanks!

**Comment by lemire** [comment]
Probabilistic filters have a fixed, non extensible capacity (given a probability).

A Counting Bloom filter, as far as I understand, is not meant to be used to repeatedly add the same key. If you do so, you will quickly suffer from overflow. Rather, you are given a capacity based on a tolerable probability and your allocated storage. And then it is assume that you insert distinct keys, not repeatedly the same key.

An Xor Filter is constructed from your keys. Of course, if you only want to insert the keys that appear rarely, you can do that, simply filter them out at construction time.

A conventional approach for these types of problems is count-min sketch.

**Comment by thomasmueller** [comment]
It is probably best if you describe the exact use case.

I assume (but you need to verify) that your use case is something like this: you have a billion or so (?) k-mers (short strings of length k over the DNA alphabet). The length is variable I assume. Then you want to assemble the DNA sequence from that. Right? So, some k-mers are very common, and you are interested in those that are relatively rare (less than 10 times). But you also want to know if some k-mers only show up once or twice (they are likely incorrect reads). So, I assume you would like to not store all the reads fully in memory and sort them, because you don't have enough memory. Instead, you would like to use a streaming algorithm.

So, you can't use xor filters for a streaming algorithm, as xor filters need to have the whole set in memory at construction time.

Count-min sketch: I'm not sure if this would work well for this case. It might. A counting Bloom filter might work better, or a hierarchy of regular Bloom filters. Or a number of cuckoo filters. For example, a special type of counting Bloom filter to check if an entry was (likely) added at least five times or more. Then a second (much smaller) counting Bloom filter, or even hash table, that contains entries that were (likely) added more than five times.

The exact algorithm would depend a lot on what you want to do, and on the statistics, the memory you have, how parallel it could be, and so on. We could likely help you, but we would need to know a lot of details. The exact algorithm to use might be custom (not one of the stock Bloom filters).

**Comment by seryrzu** [comment]
Thank you both very much, this is very helpful! I will try to add more details below.

> I assume (but you need to verify) that your use case is something like this: you have a billion or so (?) k-mers (short strings of length k over the DNA alphabet). The length is variable I assume. Then you want to assemble the DNA sequence from that. 

It is almost like that, but I do not try to assemble the genome and (at this stage) I do not work with reads. Initially, I want to index the k-mers in the genome (k-mer length is fixed). Specifically, I want to collect the set of k-mers that appear rarely in the genome (rare means "less than a threshold number of times", this threshold is 10 by default) - I am interested in them even if they are unique (appear a single time). In fact, most of k-mers will be unique, but in certain complex repeat areas there will be a lot of k-mers with high frequency that I want to filter out (higher that 10 by default, but some can have frequencies in thousands). In practice, I want to keep not the rare k-mers themselves, but their (rolling) hashes. The rolling hashes are with a prime base, can be assumed to have no collisions, and are stored in `__int128`.

I should say that I am fine with missing a few rare k-mers (reported as false frequent k-mers), but it is less preferential to report false rare k-mers.

> I assume you would like to not store all the reads fully in memory and sort them, because you don't have enough memory.

Even though, at this stage, I work with the genome and not with the reads, I would probably prefer to stream the rolling hashes while iterating over the genome rather than to store all rolling hashes (with repetitions) in memory and then sort them.

> The exact algorithm would depend a lot on what you want to do, and on the statistics, the memory you have, how parallel it could be, and so on.
The upper bound on the memory can be relatively high (20GB is OK, but storing all rolling hashes in memory probably will not fit). I am not very concerned with parallelism at the moment, so indexing can be assumed to be performed in a single thread.

My thought was to use a Counting Bloom Filter and read the genome in two passes. At the first pass, to add all rolling hashes to the filter. And at the second pass, check if it contains the query less than threshold times. That led me to the [fastfilter_cpp](https://github.com/FastFilter/fastfilter_cpp) and I glanced over Counting Bloom Filter implementations there, but seems like they don't support the threshold check? I probably can extend the code myself, but wanted to make sure first that no tested solution is out there. And, for sure, maybe other data structures are more suitable (count-min sketch or a cuckoo filter etc).

**Comment by thomasmueller** [comment]
So you have 3 billion entries. How many distinct entries (hashes) do you have, and how many of them have frequency 1-14? 

I assume you could use a 4-bit counter per unique entry (1-15 for counting, and 0 to indicate >15).

What about, first, using sampling of maybe 5%, estimate on the number of distinct entries, with HyperLogLog. Then, depending on how much memory you have, I could image you could:

* Plan A: Partially sort (using radix sort) a chunk of the entries in memory, and de-duplicate them, then store the chunk. Repeat until you processed all chunks. Then, in the second phase use merge sort. The first phase will already reduce the size a lot, and then will need 1 write + 1 read. It is easy to parallelize, and doesn't require much memory (but if you have memory, it will speed things up). The output of the second phase is a stream of rare entries.
* Plan B: Generate a chunks as above, but then generate a minimal perfect hash function (MPHF). I would still use chunks as above, and probably BBHash, which is fast, so the MPHF needs around 3-4 bits per key. At the end, each unique entry needs 8 bit of memory (4 for the MPHF + 4 for the counter). If you have enough memory (I doubt it), maybe you don't need to write and read.
* Plan C: Use a cuckoo filter with a sufficient false positive rate (e.g. 16 bit), plus, for each unique entry, a counter. That will only work if you have enough memory, maybe 24 bits per distinct key.

**Comment by seryrzu** [comment]
Thank you! After some testing, I decided to go with Plan D. Thank you again, your responses were very helpful!

**Comment by thomasmueller** [comment]
Very interesting! Thanks a lot for letting us know! I'm interested in count-min sketch (wrote a "dummy" implementation in https://github.com/thomasmueller/tinyStats). If you end up writing a paper or an open-source implementation, I would be quite interested in reading it!
