### ISSUE TITLE
False Positive Comparision Between fuse and xor16?

### ISSUE THREAD

**Issue by mpope9** [FastFilter/xor_singleheader#24]
Hello,

I've built out Erlang bindings for the binary fuse filter: https://github.com/mpope9/efuse_filter and things look very positive when benchmarking, performance-wise. I was curious on how the binary fuse filter's false positive rate compared to the xor16?

**Comment by lemire** [comment]
The latest commit (main branch) adds fuse16 filters (see updated README) which have the same false-positive probability as xor16 filters. That's 0.0015%.

Please close the issue if you feel that I have answered your question.

**Comment by lemire** [comment]
Sorry, I did not mean to close it.

**Comment by mpope9** [comment]
No problem. That answers my question, thank you.
