### ISSUE TITLE
Guard size <= 1 in binary_fuse8_allocate as the current behaviour is unsafe.

### ISSUE THREAD

**Issue by slimsag** [FastFilter/xor_singleheader#26]
I've noticed with very small input sizes (0, 1, 10, 100) that `binary_fuse8_allocate` sometimes relies on some.. questionable behavior.

For example, if called with `size=0`, `filter->Fingerprints` is ultimately allocated with `filter->ArrayLength = 786432` (768 KiB), which seems high given a filter size of zero.

With `size=1`, `sizeFactor` ends up being `INFINITY`, which makes:

https://github.com/FastFilter/xor_singleheader/blob/f190e5a9020d55c95efcef4ab136fa73ad6c743b/include/binaryfusefilter.h#L153

result in effectively:

```
uint32_t capacity = (uint32_t)(round((double)0 * INFINITY)); 
```

https://godbolt.org/z/7vqY9ofY1

or more simply:

```
uint32_t capacity = (uint32_t)((double)INFINITY); 
```

I think this cast may be undefined behavior, as in GCC this results in `-1` while in clang it results in an undefined value: 
https://godbolt.org/z/daxcT7n5K

All this to say, I think _very_ small input sizes (specifically 0, 1, 10, 100) may fail during `binary_fuse8_allocate` in the worst case scenario and, in the best case scenario, allocate a perhaps larger set of fingerprints than needed.

**Comment by lemire** [comment]
The case size <= 1 should definitively be guarded. It is a bug.

I do not see a problem with size = 10. Please elaborate if you still think that there is an issue.

**Comment by lemire** [comment]
cc @thomasmueller

**Comment by lemire** [comment]
@slimsag Thanks for the report. I shall be guarding these cases.

**Comment by lemire** [comment]
Fixed by commit https://github.com/FastFilter/xor_singleheader/commit/dabe36530e3598d648d67012c9a6362b698f5598

**Comment by slimsag** [comment]
Can confirm there is no issue with size=10. Thanks!

**Comment by lemire** [comment]
Thanks for the feedback.
