### ISSUE TITLE
BinaryFuse: reverseOrder is not fully cleared

### ISSUE THREAD

**Issue by Genbox** [FastFilter/xor_singleheader#29]
I don't really understand much of the BinaryFuse datastructure yet, but while reading through the source I noted that the reverseOrder array is not cleared completely.

Here it is initialized: https://github.com/FastFilter/xor_singleheader/blob/master/include/binaryfusefilter.h#L208
Notice that it is a length of size +1.

Here it is cleared: https://github.com/FastFilter/xor_singleheader/blob/master/include/binaryfusefilter.h#L326
Notice that it s only up to size.

If the intention is to clear the whole array, the memset should be size +1.

**Comment by lemire** [comment]
It is as intended. The last value is set once and never modified. Trace it in the code.

**Comment by lemire** [comment]
Thanks for looking at the code!
