### ISSUE TITLE
hash index issue

### ISSUE THREAD

**Issue by fankoo** [FastFilter/xor_singleheader#33]
Hi, 
thank you for your great work.
I wonder if there is a way to get the index of the hash when I found it in the set.
for example.
I have a table like below:
```
7C4A8D09CA3762AF61E59520943DC26494F8941B:23174662
F7C3BC1D808E04732ADF679965CCC34CA7AE3441:7671364
B1B3773A05C0ED0176787A4F1574FF0075F7521E:3810555
5BAA61E4C9B93F3F0682250B6CF8331B7EE68FD8:3645804
3D4F2BF07DC1BE38B20CD6E46949A1071F9D0E3D:3093220
7C222FB2927D828AF22F592134E8932480637C0D:2889079
6367C48DD193D56EA7B0BAAD25B19455E529F5EE:2834058
20EABE5D64B0E216796E834F52D61FD0B70332FC:2484157
E38AD214943DAAD1D64C102FAEC29DE4AFE9DA3D:2401761
8CB2237D0679CA88DB6464EAC60DA96345513964:2333232
01B307ACBA4F54F55AAFC33BB06BBBF6CA803E9A:2224432
601F1889667EFAEBB33B8C12572835DA3F027F78:2194818
C984AED014AEC7623A54F0591DA07A85FD4B762D:1942768
EE8D8728F435FD550F83852AABAB5234CE1DA528:1593388
7110EDA4D09E062AA5E4A390B0A572AC0D2C0220:1256907
B80A9AED8AF17118E51D4D0C2D7872AE26E2109E:1141300
B0399D2029F64D445BD131FFAA399A42D2F8E7DC:1081655
40BD001563085FC35165329EA1FF5C5ECBDBBEEF:1023001
AB87D24BDC7452E55738DEB5F868E1F16DEA5ACE:980209
AF8978B1797B72ACFFF9595A5A2A373EC3D9106D:968625
```

when i use xor8 query 7110EDA4D09E062AA5E4A390B0A572AC0D2C0220 hash and return it in the set.
how to get the index of this hash?(index=15)
thanks.

**Comment by lemire** [comment]
In general, you cannot ever tell whether the key was for sure is in the set (it is a probabilistic filter). The only thing you can know for sure is that the key is not in the set.

Of course you can add an extra data structure: e.g., if the value is possibly in the set then do a binary search through a list.
