### ISSUE TITLE
Concurrent creation and merging?

### ISSUE THREAD

**Issue by Bouncner** [FastFilter/xor_singleheader#35]
Do I understand your work correctly that it's not possible to combine multiple filters into one?

We are having a partitioned vector, which is prepared in multiple threads. We currently build BloomFilters and `and` them in the end.
Is something similar possible with the xor of binary fuse filters?

**Comment by lemire** [comment]
You compute a filter over the union of the result using Bloom filters. I don’t see how that’s possible using xor or binary fuse filters.

**Comment by Bouncner** [comment]
Ok, thanks for the quick answer!
