### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by richs27** [FastFilter/xor_singleheader#36]
Hi Daniel,

Thanks for making your fuse work available.

In your paper, " Binary Fuse Filters: Fast and Smaller Than Xor Filters", you say:
"The false positives may be later pruned after checking against the actual set."

Apologies if there is an obvious answer, but how would this pruning be achieved in a fuse8 filter?

Thanks.

**Comment by lemire** [comment]
This has nothing to do specifically with binary fuse filters or xor filters. All approximate filters (Bloom, etc.) work the same way. They have small probability of reported as present an element that is not present.

The filter itself cannot help you prune these out,  it is your job to go to the original set and check.

**Comment by richs27** [comment]
Thanks. It was a misinterpretation on my part. I was thinking there was some way of modifying the filter after creation, in order to correct false positives found.
