### ISSUE TITLE
`binary_fuse(8|16)_filter_t` forgets its size

### ISSUE THREAD

**Issue by oschonrock** [FastFilter/xor_singleheader#63]
How many keys a filter contains (ie was populated with), might be considered a basic attribute. 

However, this seems to be lost after `binary_fuse(8|16)_populate` runs.  Neither `ArrayLength` nor `SegmountCountLength` , seem to hold this information. 

Should arguably be persisted during (de-)serialization. Although would be a breaking change, since it would change the length of the serialized struct.

**Comment by lemire** [comment]
There is much metadata we could add: name, date, hash function, original data type, and so forth.

However is there any reason to believe that the users of this library cannot add the metadata they need as part of their own data structure?

The problem with adding non essentiel metadata in the core structure is that everyone pays for it whether they need it or not.

**Comment by oschonrock** [comment]
yes,.. it's a reasonable point. closing
