### ISSUE TITLE
Handle duplicated keys for the user

### ISSUE THREAD

**Issue by lemire** [FastFilter/xor_singleheader#9]
Currently the user is responsible to ensure that there are no duplicated keys. We should handle this for the user (it is relatively easy to do efficiently, without even sorting).

**Comment by thomasmueller** [comment]
Yes it would be nice. What algorithm would you use? I'm afraid I'm not aware of a very efficient one...

**Comment by lemire** [comment]
Try to construct the filter once (optimistically). The duplicated keys will be in the unmatched keys, just visit these keys.

**Comment by slimsag** [comment]
Hi! I've been trying to understand the implications of duplicated keys.. apologies if this is a naive question, but does this situation not just imply the key was already previously added to the set, and thus 'there is no work to be done' in order to add that key to the set for future testing of "is-key-in-set"?

**Comment by lemire** [comment]
@slimsag You construct a filter from a set of keys. It is assumed in the construction that the keys are distinct. If two keys are the same, then the construction will always fail because the algorithm won't manage to add both of them.

**Comment by lemire** [comment]
I have a fix in the Go version at https://github.com/FastFilter/xorfilter/pull/22

I'll port it here, but @prataprc would you be so kind to check whether it meets your need?

**Comment by prataprc** [comment]
Ported this patch to [rust-fuse8](https://github.com/bnclabs/xorfilter/commit/0fa04140b332b3c31cb32135da74f90ee169d7a2)

I have tried to measure the performance improvements for the following APIs.

`populate()` - accepts an array of keys, for each key compute the hash digest,
and insert the digest into BTreeMap for deduplication.

`populate_keys()` - accepts an array of u64 digests, and insert each digest into
BTreeMap for deduplication.

`build_keys()` - accepts an array of u64 digests, that are expected to be unique
so there is no overhead of computing the hash and inserting the hash into
BTreeMap. This can be considered as the reference performance of Fuse8 filter.

Before the patch,

```
build_keys      - 0.577 seconds # Fuse8 filter
populate_keys   - 1.610 seconds # Fuse8 filter + BTreeMap insert
populate        - 6.244 seconds # Fuse8 filter + Hash-compute + BTreeMap insert
```

After the patch

```
build_keys      - 0.555 seconds # Fuse8 filter
populate_keys   - 0.570 seconds # Fuse8 filter + BTreeMap insert
populate        - 0.720 seconds # Fuse8 filter + Hash-compute + BTreeMap insert
```

These numbers were for building 10 Million keys, and the machine used was
1st gen thread-ripper.

**Comment by lemire** [comment]
So I take it that you are happy with this solution. :-)

**Comment by lemire** [comment]
We now support a small number of duplicates. If there are too many duplicates, the user will get a reported failure but this should not happen if the hash values are fair and good.

**Comment by lemire** [comment]
Closing for now.
